### PR TITLE
SortFilter for courses

### LINKED ISSUE #205: SortFilter for courses
Allow users to sort and filter courses, similar to assignments

### PR DESCRIPTION
**Pull request by JonasWanke**
**Closes: #205**

**Screenshots**

| SortFilter sheet  | Empty state  | 🌈 Sorted by color |
| :------------: | :------------: | :-: |
| image | image | image |

### CODE REVIEW

**Comment by janrenz** [comment]
Is archived activated by default?

**Comment by janrenz** [comment]
And how cool is sorted by Color :)

**Comment by JonasWanke** [comment]
@janrenz Archived courses are filtered out by default. The first screenshot in the description shows the default configuration.

**Review by MarcelGarus — APPROVED** [review]
Looks great!
In the long term, do you think it might make sense to put part of the sorting into another package? Seems like it's generic enough to be used in other apps too.

**Comment by janrenz** [comment]
Maybe an indicator that filters are set would be nice, but in this case this is difficult because we have a default filter form the start. Maybe something for the UX backlog.

**Comment by JonasWanke** [comment]
@marcelgarus I'll probably do that soon. I wasn't yet convinced about generic applicability, but now with more features being added it probably makes sense.

@janrenz Maybe we can do that in combination with #169  – show a row of suggested filter chips, where the active one stays selected. If the user selects a custom configuration, we instead show a selected "custom" chip:
|   |   |
|:-:|:-:|
| image |image|

(Just a quick UI prototype)

**Pull request merged**
