### PR TITLE
fix(app): some pods are missing default values

### LINKED ISSUE #262: Fix cocoapods
**Describe the bug**
When trying to build for iOS, several errors related to Cocoa Pods occur.

**Environment:**

- Device:  Virtual iPhone 11 Pro Max
- OS version:  iOS 13.4
- App version:  latest

### PR DESCRIPTION
**Pull request by phpfs**
**Closes: #262**

We now add default values for pods - e.g. Swift version.

### CODE REVIEW

**Comment by JonasWanke** [comment]
Our GitHub action workflows seem to fail due to this PR originating from a fork. As it only contains pure iOS changes which we currently don't test, we can probably ignore their failure for now.

**Comment by janrenz** [comment]
Hi, i tired this fix, and I compiled one time (and the crashed with a hive error). So I checked out a clean master and copied the pod file over, I also clear all temp files I am aware of. I receive this error on compiling:

Xcode's output:
↳
    /Users/jan/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwe
    bview-2.1.0+1/ios/Classes/InAppWebViewFlutterPlugin.m:19:9: fatal error:
    'flutter_inappwebview-Swift.h' file not found
    #import <flutter_inappwebview-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Anything else I need to set in Xcode or somewhere else?

**Review by janrenz — COMMENTED** [review]
Should we commit the pod file.lock as well? 
I also still have problems to compile I Xcode, see my comment

**Comment by janrenz** [comment]
Also, if you want to feel free to add yourself to the in app contributor list

**Pull request merged**
